### ISSUE TITLE
すみません、質問したいので、、

### ISSUE THREAD

**Issue by revTimo** [hamano/dotfiles#1]
すみません、全然関係ないことと思いますが、AAA blogにマイナンバーカードでSSHするという記事を書いた方ですか？　
どうしても質問したいので、ここから問い合わせました。申し訳ございません。よろしければ質問させていただいてもいいですか？

**Comment by hamano** [comment]
OpenSC関連であれば[こちら](https://github.com/jpki/OpenSC/)のissueにご質問いただければ、可能であれば回答します。
